<?php
// This file is generated by /Users/andrew/wm-dev/vagrant/mediawiki/skins/LivingStyleGuide, do not adjust manually

global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'LivingStyleGuideSkinTemplate' => __DIR__ . '/src/LivingStyleGuideSkinTemplate.php',
	'SkinLivingStyleGuide' => __DIR__ . '/src/SkinLivingStyleGuide.php',
);
