<?php
// This file is generated by /vagrant/mediawiki/extensions/LightNCandySkin, do not adjust manually

global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'AbstractTemplateSkin' => __DIR__ . '/AbstractTemplateSkin.php',
	'LightNCandyTemplate' => __DIR__ . '/AbstractLightNCandyTemplate.php',
	'SkinTest' => __DIR__ . '/test/SkinTest.php',
	'TestSkinTemplate' => __DIR__ . '/test/TestSkinTemplate.php',
);
